language: php
services:
  - mysql-server
php:
  - 7.1.11
dist: trusty
sudo: true
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  ssh_known_hosts:
    - ${DEPLOY_HOST}
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS vault;'
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install -n
  - cp .env.example .env
  - php artisan migrate
  - php artisan db:seed
  - vendor/bin/phpunit --coverage-clover=coverage.xml
script:
# You must setup your own keys and customize your own command for your own instance of vault
# - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv
  # -in scripts/deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "Unicorn Time"
deploy:
  - provider: script
    script: ./scripts/travis.sh
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: ./scripts/travis.sh
    skip_cleanup: true
    on:
      branch: master
