language: php
services:
- mysql
php:
- 7.1.11
dist: trusty
sudo: true
before_install:
- sudo service mysql stop || echo "mysql not stopped"
- sudo stop mysql-5.6 || echo "mysql-5.6 not stopped"
- echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
- wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
- sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
- sudo mysql_upgrade
- mysql -e 'CREATE DATABASE IF NOT EXISTS vault;'
- composer self-update
- composer validate --no-check-all --ansi
- composer install -n
- cp .env.example .env
- php artisan migrate
- php artisan db:seed
- vendor/bin/phpunit --coverage-clover=coverage.xml
script:
# You must setup your own keys and customize your own command for your own instance of vault
# - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv
  # -in scripts/deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts:
    - ${DEPLOY_HOST}
after_success:
- bash <(curl -s https://codecov.io/bash)
- echo "Unicorn Time"
deploy:
  - provider: script
    script: ./scripts/travis.sh
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: ./scripts/travis.sh
    skip_cleanup: true
    on:
      branch: master
